[pytest]
minversion = 7.0
addopts = -v -rA --html=outputs/report.html --self-contained-html
python_files = tests/**/*.py test_*.py *_test.py
markers =
    smoke: mark a smoke test
    regression: mark a regression test
